language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/ci-playground/experimental"


matrix:
    include:
    - env: COMPILER=gcc-7
    - env: COMPILER=clang-5


before_install:
  - docker pull ${DOCKER_IMG}/${COMPILER}:latest

script:
  - if [[ "${COMPILER}" == "arm-none-eabi-gcc" ]]; then ARGS="-e CC=arm-none-abi-gcc -e CXX=arm-none-eabi-g++ -e BUILD_TYPE -e LTO_ENABLED"; fi
  - docker run -v ${PWD}:/mnt ${ARGS} -it ${DOCKER_IMG}/${COMPILER} /bin/bash -c "cd /mnt; script/ci_build.sh"

