language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/ci-playground/experimental"


matrix:
    include:
    - env: COMPILER=gcc-7
    - env: COMPILER=gcc-6
    - env: COMPILER=clang-5
    - env: COMPILER=clang-4
    - env: COMPILER=arm-none-eabi-gcc BUILD_TYPE=Debug
    - env: COMPILER=arm-none-eabi-gcc BUILD_TYPE=Release
    - env: COMPILER=arm-none-eabi-gcc BUILD_TYPE=MinSizeRel
    - env: COMPILER=arm-none-eabi-gcc BUILD_TYPE=MinSizeRel LTO_ENABLED=ON


before_install:
  - docker pull ${DOCKER_IMG}/${COMPILER}:latest

script:
  - if [[ "${COMPILER}" == "arm-none-eabi-gcc" ]]; then ARGS="-e CC=arm-none-abi-gcc -e CXX=arm-none-eabi-g++"; fi
  - docker run -v ${PWD}:/mnt -it ${DOCKER_IMG}/${COMPILER} ${ARGS} /bin/bash -c "cd /mnt; script/ci_build.sh"

