language: generic

dist: trusty
sudo: required


env:
  global:
    - DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependencies"
    - CMAKE_VERSION="3.9"

cache:
    directories:
        - ${DEPENDENCY_DIR}


matrix:
    include:
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
          sources: &sources
            - ubuntu-toolchain-r-test


install:
    - pwd && ls
    - mkdir -p "${DEPENDENCY_DIR}" && cd "${DEPENDENCY_DIR}"
    - |
        if [[ ! -d "$(ls -A ${DEPENDENCY_DIR}/cmake)" ]]; then
          CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.0-Linux-x86_64.tar.gz"
          mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
        fi
        export PATH="${DEPENDENCY_DIR}/cmake/bin:${PATH}"
    - pwd && ls
    - cmake --version

before_script:
    - cd ${TRAVIS_BUILD_DIR}

script:
    - pwd && ls
    - if [[ "$CXX" == clang* ]]; then export CXXFLAGS="-stdlib=libc++"; fi
    - script/ci_build.sh
    - pwd && ls

before_install:
    - pwd && ls
    - script/ci_install.sh
    - pwd && ls

