language: generic

dist: trusty
sudo: required

cache:
    apt: true

matrix:
    include:
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
            - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: *sources
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
          sources: *sources
    - env: CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          packages:
            - clang-3.7
            - libc++-dev
          sources: *sources
    - env: CXX=clang++-3.6 CC=clang-3.6
      addons:
        apt:
          packages:
            - clang-3.6
            - libc++-dev
          sources: *sources
    - env: CXX=arm-none-eabi-g++ CC=arm-none-eabi-gcc BUILD_TYPE=Debug
      addons:
        apt:
          packages:
            - gcc-arm-embedded
          sources: *sources
    - env: CXX=arm-none-eabi-g++ CC=arm-none-eabi-gcc BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - gcc-arm-embedded
          sources: *sources
    - env: CXX=arm-none-eabi-g++ CC=arm-none-eabi-gcc BUILD_TYPE=MinSizeRel
      addons:
        apt:
          packages:
            - gcc-arm-embedded
          sources: *sources

script:
    - script/travis_build.sh

before_install:
    - script/travis_install.sh
